- job:
    name: preserve-builder-reimage
    project-type: pipeline
    description: "Pipeline to reimage Jenkins builders and run post-reimage ansible tasks"

    concurrent: false

    parameters:
      - choice:
          name: ACTION
          choices:
            - reimage
            - reimage-all
            - wait_online (debug)
          default: reimage
          description: "Reimage action"
      - string:
          name: MACHINE
          default: ""
          description: "Machine(s) :<br>node1<br>node1,node2<br>node1:jammy,node2:centos9"
      - string:
          name: OS
          default: ""
          description: "Optional OS (e.g. jammy, centos9).<br>Applies to all unless overridden"
      - bool:
          name: SKIP_REIMAGE
          default: false
          description: "Skip reimage and only run post-reimage tasks"

    scm:
      - git:
          url: https://github.com/ceph/ceph-build.git
          branches:
            - builder-reimage
          clean: true

    pipeline-scm:
      scm:
        - git:
            url: https://github.com/ceph/ceph-build.git
            branches:
              - builder-reimage
      script-path: builder-reimage/Jenkins-job/prod-jenkins/jenkins-pipeline/build/Jenkinsfile
      lightweight-checkout: true
