- job:
    name: ceph-pr-docs
    display-name: 'ceph: Pull Requests Docs Check'
    concurrent: true
    node: jammy && x86_64
    project-type: freestyle
    defaults: global
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    properties:
      - github:
          url: https://github.com/ceph/ceph
      - build-discarder:
          days-to-keep: 14

    discard-old-builds: true

    triggers:
      - github-pull-request:
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          cancel-builds-on-update: true
          only-trigger-phrase: false
          trigger-phrase: 'jenkins test docs.*'
          github-hooks: true
          permit-all: false
          auto-close-on-fail: false
          status-context: "Docs: build check"
          started-status: "Docs: building"
          success-status: "OK - docs built"
          failure-status: "Docs: failed with errors"

      - generic-webhook-trigger:
          token-credential-id: ci-approved-trigger-token
          print-contrib-var: true
          post-content-params:
            - type: JSONPath
              key: action
              value: $.action
            - type: JSONPath
              key: label
              value: $.label.name
            - type: JSONPath
              key: ghprbPullId
              value: $.pull_request.number
            - type: JSONPath
              key: ghprbTargetBranch
              value: $.pull_request.base.ref
            - type: JSONPath
              key: ghprbSourceBranch
              value: $.pull_request.head.ref
            - type: JSONPath
              key: ghprbActualCommit
              value: $.pull_request.head.sha
            - type: JSONPath
              key: sha1
              value: $.pull_request.head.sha
          regex-filter-text: '$action $label $ghprbPullId'
          regex-filter-expression: '^labeled ci-approved \d+$'
          cause: 'PR #$ghprbPullId labeled ci-approved'

    scm:
      - git:
          url: https://github.com/ceph/ceph
          browser: auto
          branches:
            - ${{sha1}}
          refspec: +refs/pull/${{ghprbPullId}}/*:refs/remotes/origin/pr/${{ghprbPullId}}/*
          skip-tag: true
          shallow-clone: true
          honor-refspec: true
          timeout: 20
          wipe-workspace: true

    builders:
      - shell:
          !include-raw-verbatim: ../../build/build

    wrappers:
      - credentials-binding:
          - file:
              credential-id: cephacheck.2020-04-29.private-key.pem
              variable: GITHUB_CHECK_PKEY_PEM
