#!/bin/bash
set -ex

if grep -q  debian /etc/*-release; then
    sudo bash -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
    wget https://dl.google.com/linux/linux_signing_key.pub
    sudo apt-key add linux_signing_key.pub
    sudo apt-get update
    sudo apt-get install -y google-chrome-stable
    sudo apt-get install -y python-requests python-openssl python-jinja2

elif grep -q rhel /etc/*-release; then
    sudo dd of=/etc/yum.repos.d/google-chrome.repo status=none <<EOF
[google-chrome]
name=google-chrome
baseurl=https://dl.google.com/linux/chrome/rpm/stable/x86_64
enabled=1
gpgcheck=1
gpgkey=https://dl.google.com/linux/linux_signing_key.pub
EOF
    sudo yum install -y google-chrome-stable
    sudo yum install -y python-requests pyOpenSSL python-jinja2
fi
