- job:
    name: ceph-dev-setup
    description: "This job step checks out the branch and builds the tarballs, diffs, and dsc that are passed to the ceph-dev-build step.\r\n\r\nNotes:\r\nJob needs to run on a releatively recent debian system.  The Restrict where run feature is used to specifiy an appropriate label.\r\nThe clear workspace before checkout box for the git plugin is used."
    node: huge && bionic && !arm64
    display-name: 'ceph-dev-setup'
    block-downstream: false
    block-upstream: false
    concurrent: true
    properties:
      - build-discarder:
          num-to-keep: 100
          artifact-num-to-keep: 50
      - github:
          url: https://github.com/ceph/ceph
      - copyartifact:
          projects: ceph-dev-build,ceph-dev,preserve-adarsha-test

    parameters:
      - string:
          name: BRANCH
          description: "The git branch (or tag) to build"

    scm:
      - git:
          url: git@github.com:ceph/ceph.git
          # Use the SSH key attached to the ceph-jenkins GitHub account.
          credentials-id: 'jenkins-build'
          branches:
            - $BRANCH
          skip-tag: true
          wipe-workspace: true

    builders:
      - shell:
          !include-raw-verbatim:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    publishers:
      - archive:
          artifacts: 'dist/**'
          allow-empty: false
          latest-only: false

      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                  - FAILURE
                  - ABORTED
              build-steps:
                - shell:
                    !include-raw-verbatim:
                      - ../../../scripts/build_utils.sh
                      - ../../build/failure

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
          - text:
              credential-id: shaman-api-key
              variable: SHAMAN_API_KEY
