- scm:
    name: mita
    scm:
      - git:
          url: https://github.com/ceph/mita.git
          branches:
            - main
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: true

- job:
    name: mita-deploy
    node: built-in
    description: "This job clones mita and deploys it to its production server based on the BRANCH value"
    display-name: 'mita-deploy'
    block-downstream: false
    block-upstream: false
    properties:
      - build-discarder:
          days-to-keep: -1
          num-to-keep: 25
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/mita

    parameters:
      - string:
          name: BRANCH
          description: "The git branch (or tag) to build, defaults to 'main'"
          default: "main"
    scm:
      - mita

    triggers:
      - github

    builders:
      - shell:
          !include-raw-verbatim:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
