#!/usr/bin/env bash
set -o errexit
set -o pipefail

if [[ -z $CEPH_WIN_CI_KEY ]]; then
    echo "ERROR: The CI SSH private key secret (CEPH_WIN_CI_KEY) is not set"
    exit 1
fi

export VM_IMAGE_URL=${VM_IMAGE_URL:-"https://filedump.ceph.com/windows/ceph-win-ltsc2019-ci-image.qcow2"}
export VM_NAME=${VM_NAME:-"ceph-win-ltsc2019-${JOB_NAME}-${BUILD_ID}"}

export SSH_USER="administrator"
export SSH_KNOWN_HOSTS_FILE="$WORKSPACE/known_hosts"
export SSH_KEY="$CEPH_WIN_CI_KEY"


#
# Install requirements (if needed)
#
if ! which virt-install >/dev/null; then
    sudo apt-get update
    sudo apt-get install -y virtinst
fi
if ! sudo virsh net-info default &>/dev/null; then
    cat << EOF > $WORKSPACE/default-net.xml
<network>
  <name>default</name>
  <bridge name="virbr0"/>
  <forward mode="nat"/>
  <ip address="192.168.122.1" netmask="255.255.255.0">
    <dhcp>
      <range start="192.168.122.2" end="192.168.122.254"/>
    </dhcp>
  </ip>
</network>
EOF
    sudo virsh net-define $WORKSPACE/default-net.xml
    sudo virsh net-start default
    sudo virsh net-autostart default
    rm $WORKSPACE/default-net.xml
fi

#
# Download the Windows qcow2 image
#
IMAGE_FILE="$(basename $VM_IMAGE_URL)"
echo "Downloading VM image from $VM_IMAGE_URL"
curl -L -o ${WORKSPACE}/${IMAGE_FILE} $VM_IMAGE_URL

#
# Start the Windows testing VM
#
sudo virt-install \
    --name $VM_NAME \
    --os-variant win2k19 \
    --boot hd \
    --virt-type kvm \
    --graphics spice \
    --cpu host \
    --vcpus 4 \
    --memory 4096 \
    --disk ${WORKSPACE}/${IMAGE_FILE},bus=virtio \
    --network network=default,model=virtio \
    --controller type=virtio-serial \
    --channel unix,target_type=virtio,name=org.qemu.guest_agent.0 \
    --noautoconsol

#
# Wait until the QEMU agent reports the VM IP, and it's reachable via SSH
#
SECONDS=0
TIMEOUT=600
SLEEP_SECS=10
while true; do
    if [[ $SECONDS -gt $TIMEOUT ]]; then
        echo "Timeout waiting for the VM to start"
        exit 1
    fi
    VM_IP=$(sudo virsh domifaddr --source agent --interface Ethernet --full $VM_NAME | grep ipv4 | awk '{print $4}' | cut -d '/' -f1) || {
        echo "Retrying in $SLEEP_SECS seconds"
        sleep $SLEEP_SECS
        continue
    }
    ssh-keyscan -H $VM_IP &> ${WORKSPACE}/known_hosts || {
        echo "SSH is not reachable yet"
        sleep $SLEEP_SECS
        continue
    }
    SSH_ADDRESS=$VM_IP ssh_exec hostname || {
        echo "Cannot execute SSH commands yet"
        sleep $SLEEP_SECS
        continue
    }
    break
done
export SSH_ADDRESS=$VM_IP
