- job:
    name: ceph-pr-clang-tidy
    node: jammy && small
    project-type: freestyle
    defaults: global
    display-name: 'ceph: Clang-tidy checks'
    concurrent: true
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - build-discarder:
          days-to-keep: 15
          artifact-days-to-keep: 15
          
    parameters:
      - string:
          name: BRANCH
          default: main
  triggers:
  - github-pull-request:
      allow-whitelist-orgs-as-admins: true
      org-list:
        - ceph
      only-trigger-phrase: false
      status-context: "Clang-tidy lint check"
      started-status: "checking if bugs exist"
      success-status: "no bugs found"
      failure-status: "bugs found"

  scm:
    - git:
        url: https://github.com/ceph/ceph.git
        branches:
          - $BRANCH
        browser: auto
        timeout: 20
        shallow-clone: true
        wipe-workspace: true

  builders:
  - copyartifact:
      project: ceph-pull-requests

  - shell:
      !include-raw:
        - ../../../scripts/build_utils.sh
        - ../../build/build
        - ../../build/clang-tidy-to-junit.py

  publishers:
  - junit:
      results: report.xml
      allow-empty-results: true
