- job:
    name: ceph-qa-suite-pull-requests
    node: trusty
    project-type: freestyle
    defaults: global
    concurrent: true
    display-name: 'ceph-qa-suite: Pull Requests'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - build-discarder:
          days-to-keep: 15
          num-to-keep: 30
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph-qa-suite/

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          admin-list:
            - alfredodeza
            - ktdreyer
          org-list:
            - ceph
          white-list:
            - jcsp
            - gregsfortytwo
            - dmick
            - GregMeno
            - dzafman
            - dillaman
            - dachary
            - liewegas
          trigger-phrase: ''
          only-trigger-phrase: false
          github-hooks: true
          permit-all: false
          auto-close-on-fail: false

    scm:
      - git:
          url: https://github.com/ceph/ceph-qa-suite.git
          branches:
            - ${{sha1}}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: false

    builders:
      - shell:
          !include-raw-verbatim:
            - ../../../scripts/build_utils.sh
            - ../../build/build
