- job:
    name: ceph-deploy-docs
    node: docs
    project-type: freestyle
    defaults: global
    display-name: 'ceph-deploy: docs build'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - build-discarder:
          days-to-keep: -1
          num-to-keep: 10
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph-deploy

    triggers:
      - github

    scm:
      - git:
          url: https://github.com/ceph/ceph-deploy
          branches:
            - main
          browser: auto
          skip-tag: true
          timeout: 20

    builders:
      - shell:
          !include-raw-verbatim:
            - ../../../scripts/build_utils.sh
            - ../../build/build
