- job:
    name: ceph-docs
    node: docs
    project-type: freestyle
    defaults: global
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    properties:
      - build-discarder:
          days-to-keep: 1
          num-to-keep: 10
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph
    discard-old-builds: true

    triggers:
      - github

    scm:
      - git:
          url: https://github.com/ceph/ceph
          browser: auto
          # The default is to build and publish every branch.
          # Uncomment this for testing:
          #branches:
          #  - 'origin/main'
          skip-tag: true
          timeout: 20
          wipe-workspace: true

    builders:
      - shell:
          !include-raw-verbatim: ../../build/build
