- job:
    name: radosgw-agent
    node: small && trusty
    project-type: matrix
    defaults: global
    display-name: 'radosgw-agent'
    concurrent: true
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3

    parameters:
      - string:
          name: BRANCH
          description: "The git branch or tag to build"
          default: main

      - bool:
          name: RELEASE
          description: "If checked, it will use the key for releases, otherwise it will use the autosign one."
          default: true

      - bool:
          name: TEST
          description: "
If this is unchecked, then the builds will be pushed to chacra with the correct ref. This is the default.

If this is checked, then the builds will be pushed to chacra under the 'test' ref."

      - bool:
          name: FORCE
          description: "
If this is unchecked, then then nothing is built or pushed if they already exist in chacra. This is the default.

If this is checked, then the binaries will be built and pushed to chacra even if they already exist in chacra."
          default: true

    scm:
      - git:
          skip-tag: true
          url: https://github.com/ceph/radosgw-agent.git
          branches:
            - $BRANCH
          browser: auto
          timeout: 20

    axes:
      - axis:
          type: label-expression
          name: ARCH
          values:
            - x86_64
      - axis:
          type: label-expression
          name: DIST
          values:
            - wheezy
            - precise
            - trusty
            - jessie
            - centos6
            - centos7

    builders:
      - shell:
          !include-raw-verbatim:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
