- scm:
    name: ceph-build
    scm:
      - git:
          url: https://github.com/ceph/ceph-build.git
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: true
          basedir: "ceph-build"
          branches:
            - origin/master

- job:
    name: ceph-tag
    node: trusty
    description: "This job clones from upstream Ceph, sets the right version from the tag and pushes changes to ceph-releases"
    display-name: 'ceph-tag'
    block-downstream: false
    block-upstream: false
    properties:
      - build-discarder:
          days-to-keep: -1
          num-to-keep: 25
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph

    parameters:
      - string:
          name: BRANCH
          description: "The git branch (or tag) to build"
      - string:
          name: VERSION
          description: "The version for release, e.g. 0.94.4"
    scm:
      - ceph-build

    builders:
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - ssh-agent-credentials:
          # "jenkins-build" SSH key, needed so we can push to
          # ceph-deploy.git
          user: 'jenkins-build'
