- job:
    name: ceph-deploy
    project-type: multijob
    defaults: global
    display-name: 'ceph-deploy'
    concurrent: true
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3

    parameters:
      - string:
          name: BRANCH
          description: "The git branch or tag to build. Defaults to main"
          default: "main"

      - bool:
          name: TEST
          description: "
If this is unchecked, then the builds will be pushed to chacra with the correct ref. This is the default.

If this is checked, then the builds will be pushed to chacra under the 'test' ref."

      - bool:
          name: TAG
          description: "When this is checked, Jenkins will remove the previous tag and recreate it again, changing the control files and committing again. When this is unchecked, Jenkins will not do any commit or tag operations. If you've already created the private tag separately, then leave this unchecked.
Defaults to checked."
          default: true

      - bool:
          name: FORCE
          description: "
If this is unchecked, then then nothing is built or pushed if they already exist in chacra. This is the default.

If this is checked, then the binaries will be built and pushed to chacra even if they already exist in chacra."

      - string:
          name: VERSION
          description: "The version for release, e.g. 0.94.4"

    builders:
      - multijob:
          name: 'ceph-deploy tag phase'
          condition: SUCCESSFUL
          projects:
            - name: ceph-deploy-tag
              current-parameters: true
              exposed-scm: false

      - multijob:
          name: 'ceph-deploy build phase'
          condition: SUCCESSFUL
          projects:
            - name: ceph-deploy-build
              current-parameters: true
              exposed-scm: false

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
