- job:
    name: artifacts-test
    project-type: pipeline
    concurrent: true
    pipeline-scm:
      scm:
        - git:
            url: https://github.com/ceph/ceph-build
            branches:
              - ${{CEPH_BUILD_BRANCH}}
            shallow-clone: true
            submodule:
              disable: true
            wipe-workspace: true
      script-path: artifacts-test/build/Jenkinsfile
      lightweight-checkout: true
      do-not-fetch-tags: true

    parameters:
      - string:
          name: CEPH_BUILD_BRANCH
          description: "Use the Jenkinsfile from this ceph-build branch"
          default: pipeline-container
