- job:
    name: ceph-container-build-ceph-base-push-imgs
    node: huge && trusty && x86_64
    project-type: freestyle
    defaults: global
    display-name: ceph-container-build-ceph-base-push-imgs
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - build-discarder:
          days-to-keep: 1
          num-to-keep: 1
          artifact-days-to-keep: 1
          artifact-num-to-keep: 1
      - github:
          url: https://github.com/ceph/ceph-container

    triggers:
      - timed: '@daily'

    parameters:
      - string:
          name: X86_64_FLAVORS_TO_BUILD
          description: "x86 flavor(s) to build"
          default: "pacific,centos,8 quincy,centos,8 reef,centos,8"

    scm:
      - git:
          url: https://github.com/ceph/ceph-container.git
          branches:
            - main
          browser: auto
          basedir: "ceph-container"
          timeout: 20

    builders:
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
          - username-password-separated:
              credential-id: ceph-container-quay-io
              username: REGISTRY_USERNAME
              password: REGISTRY_PASSWORD
