- job:
    name: ceph-osc-trigger
    disabled: true
    node: master
    project-type: freestyle
    defaults: global
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    properties:
      - build-discarder:
          days-to-keep: 1
          num-to-keep: 10
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph-ci
    discard-old-builds: true

    triggers:
      - github

    scm:
      - git:
          url: https://github.com/ceph/ceph-ci
          browser: auto
          skip-tag: true
          timeout: 20
          wipe-workspace: true

    builders:
      #- conditional-step:
      #    condition-kind: regex-match
      #    regex: .*(jewel|kraken|luminous).*
      #    label: '${GIT_BRANCH}'
      #    on-evaluation-failure: dont-run
      #    steps:
      #      - shell:
      #          !include-raw:
      #          - ../../../scripts/build_utils.sh
      #          - ../../build/notify
      #      - trigger-builds:
      #          - project: 'ceph-osc'
      #            predefined-parameters: |
      #              BRANCH=${GIT_BRANCH}
      #              FORCE=True
      #          - project: 'ceph-osc'
      #            predefined-parameters: |
      #              BRANCH=${GIT_BRANCH}
      #              FORCE=True
      #              FLAVOR=notcmalloc
      #- conditional-step:
      #    condition-kind: shell
      #    condition-command: |
      #      echo "${GIT_BRANCH}" | grep '\(mimic\|nautilus\)'
      #    on-evaluation-failure: dont-run
      #    steps:
      #      - shell:
      #          !include-raw:
      #          - ../../../scripts/build_utils.sh
      #          - ../../build/notify
      #      - trigger-builds:
      #          - project: 'ceph-osc'
      #            predefined-parameters: |
      #              BRANCH=${GIT_BRANCH}
      #              FORCE=True
      #              DISTROS=bionic xenial centos7
      #          - project: 'ceph-osc'
      #            predefined-parameters: |
      #              BRANCH=${GIT_BRANCH}
      #              FORCE=True
      #              DISTROS=centos7
      #              FLAVOR=notcmalloc
      - conditional-step:
          condition-kind: shell
          condition-command: |
            echo "${GIT_BRANCH}" | grep -v '\(jewel\|kraken\|luminous\|mimic\|nautilus\)'
          on-evaluation-failure: dont-run
          steps:
            - shell:
                !include-raw:
                - ../../../scripts/build_utils.sh
                - ../../build/notify
            - trigger-builds:
                - project: 'ceph-osc'
                  predefined-parameters: |
                    BRANCH=${GIT_BRANCH}
                    FORCE=True
                    DISTROS=leap15
                #- project: 'ceph-osc'
                #  predefined-parameters: |
                #    BRANCH=${GIT_BRANCH}
                #    FORCE=True
                #    DISTROS=centos7
                #    FLAVOR=notcmalloc
                #- project: 'ceph-osc'
                #  predefined-parameters: |
                #    BRANCH=${GIT_BRANCH}
                #    FORCE=True
                #    DISTROS=bionic
                #    FLAVOR=crimson

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
          - text:
              credential-id: shaman-api-key
              variable: SHAMAN_API_KEY
