- job:
    name: lab-cop
    node: small && xenial
    defaults: global
    display-name: 'lab-cop'
    properties:
      - build-discarder:
          days-to-keep: 15
          num-to-keep: 30
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1

    builders:
      - shell:
          !include-raw-verbatim:
            - ../../build/build

