- scm:
    name: ceph-build
    scm:
      - git:
          url: https://github.com/ceph/ceph-build.git
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: true
          basedir: "ceph-build"
          branches:
            - origin/main

- job:
    name: ceph-deploy-tag
    description: "This job clones ceph-deploy and sets the right version from the tag, pushing back to ceph-deploy.git"
    display-name: 'ceph-deploy-tag'
    node: 'trusty&&small'
    block-downstream: false
    block-upstream: false
    properties:
      - build-discarder:
          days-to-keep: -1
          num-to-keep: 25
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph-deploy

    parameters:
      - string:
          name: BRANCH
          description: "The git branch (or tag) to build"
          default: "main"
      - string:
          name: VERSION
          description: "The version for release, e.g. 1.5.30"
    scm:
      - ceph-build

    builders:
      - shell:
          !include-raw-verbatim:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - ssh-agent-credentials:
          # "jenkins-build" SSH key, needed so we can push to
          # ceph-deploy.git
          user: 'jenkins-build'
