- job:
    name: ceph-pr-submodules
    node: small
    project-type: freestyle
    defaults: global
    display-name: 'ceph: Pull Request modified submodules'
    concurrent: true
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - build-discarder:
          days-to-keep: 15
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph/

    parameters:
      - string:
          name: sha1
          description: "commit id or a refname, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          trigger-phrase: 'jenkins test submodules'
          only-trigger-phrase: false
          github-hooks: true
          permit-all: false
          auto-close-on-fail: false
          status-context: "Unmodified Submodules"
          started-status: "checking if PR has modified submodules"
          success-status: "submodules for project are unmodified"
          failure-status: "Approval needed: modified submodules found"

      - generic-webhook-trigger:
          token-credential-id: ci-approved-trigger-token
          print-contrib-var: true
          post-content-params:
            - type: JSONPath
              key: action
              value: $.action
            - type: JSONPath
              key: label
              value: $.label.name
            - type: JSONPath
              key: ghprbPullId
              value: $.pull_request.number
            - type: JSONPath
              key: ghprbTargetBranch
              value: $.pull_request.base.ref
            - type: JSONPath
              key: ghprbSourceBranch
              value: $.pull_request.head.ref
            - type: JSONPath
              key: ghprbActualCommit
              value: $.pull_request.head.sha
            - type: JSONPath
              key: sha1
              value: $.pull_request.head.sha
          regex-filter-text: '$action $label $ghprbPullId'
          regex-filter-expression: '^labeled ci-approved \d+$'
          cause: 'PR #$ghprbPullId labeled ci-approved'

    scm:
      - git:
          url: https://github.com/ceph/ceph.git
          branches:
            - ${{sha1}}
          refspec: +refs/pull/${{ghprbPullId}}/*:refs/remotes/origin/pr/${{ghprbPullId}}/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: true

    builders:
      - shell:
          !include-raw-verbatim:
            - ../../build/build
