- job:
    name: ceph-deploy-build
    node: small && trusty
    project-type: matrix
    defaults: global
    display-name: 'ceph-deploy-build'
    concurrent: true
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3

    scm:
      - git:
          url: https://github.com/ceph/ceph-deploy.git
          branches:
            - $BRANCH
          browser: auto
          skip-tag: true
          timeout: 20
          wipe-workspace: true

    axes:
      - axis:
          type: label-expression
          name: ARCH
          values:
            - x86_64
      - axis:
          type: label-expression
          name: DIST
          values:
            - bionic
            - centos7
            - centos8

    builders:
      - shell:
            !include-raw-verbatim:
              - ../../../scripts/build_utils.sh
              - ../../build/setup
              - ../../build/build

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
          - text:
              credential-id: chacractl-key
              variable: CHACRACTL_KEY
          - text:
              credential-id: shaman-api-key
              variable: SHAMAN_API_KEY
