- job:
    name: ceph-ansible-docs
    node: docs
    project-type: freestyle
    defaults: global
    display-name: 'ceph-ansible: docs build'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - build-discarder:
          days-to-keep: -1
          num-to-keep: 10
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph-ansible

    triggers:
      - github

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible
          branches:
            - main
            - stable-2.1
            - stable-2.2
            - stable-3.0
            - stable-3.1
            - stable-3.2
            - stable-4.0
            - stable-5.0
            - stable-6.0
          browser: auto
          skip-tag: true
          timeout: 20

    builders:
      - shell:
          !include-raw-verbatim:
            - ../../../scripts/build_utils.sh
            - ../../build/build
