- job:
    name: ceph-next
    description: 'This is the main ceph build task which uses chacra.ceph.com.'
    project-type: multijob
    defaults: global
    disabled: false
    display-name: 'ceph-next'
    concurrent: false
    logrotate:
      daysToKeep: -1
      numToKeep: 25
      artifactDaysToKeep: 25
      artifactNumToKeep: 25
    block-downstream: false
    block-upstream: false
    properties:
      - github:
          url: https://github.com/ceph/ceph

    parameters:
      - string:
          name: BRANCH
          description: "The git branch (or tag) to build"
          default: master

      - bool:
          name: TEST
          description: "
If this is unchecked, then the builds will be pushed to chacra with the correct ref. This is the default.

If this is checked, then the builds will be pushed to chacra under the 'test' ref."

    builders:
      - multijob:
          name: 'ceph setup phase'
          condition: SUCCESSFUL
          projects:
            - name: ceph-setup-next
              current-parameters: true
              exposed-scm: false
      - multijob:
          name: 'ceph build phase'
          condition: SUCCESSFUL
          projects:
            - name: ceph-build-next
              current-parameters: true
              exposed-scm: false

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
