- job:
    name: cephmetrics
    project-type: matrix
    defaults: global
    display-name: 'cephmetrics'
    block-downstream: false
    block-upstream: false
    concurrent: true
    properties:
      - github:
          url: https://github.com/ceph/cephmetrics
    parameters:
      - string:
          name: BRANCH
          description: "The git branch (or tag) to build"
          default: "main"

      - string:
          name: DISTROS
          description: "A list of distros to build for. Available options are: centos7, centos6"
          default: "centos7"

      - string:
          name: ARCHS
          description: "A list of architectures to build for. Available options are: x86_64, and arm64"
          default: "x86_64"

      - bool:
          name: FORCE
          description: "
If this is unchecked, then nothing is built or pushed if they already exist in chacra. This is the default.

If this is checked, then the binaries will be built and pushed to chacra even if they already exist in chacra."

      - string:
          name: BUILD_VIRTUALENV
          description: "Base parent path for virtualenv locations, set to avoid issues with extremely long paths that are incompatible with tools like pip. Defaults to '/tmp/' (note the trailing slash, which is required)."
          default: "/tmp/"

    execution-strategy:
       combination-filter: DIST==AVAILABLE_DIST && ARCH==AVAILABLE_ARCH && (ARCH=="x86_64" || (ARCH == "arm64" && (DIST == "xenial" || DIST == "centos7")))
    axes:
      - axis:
          type: label-expression
          name: MACHINE_SIZE
          values:
            - small
      - axis:
          type: label-expression
          name: AVAILABLE_ARCH
          values:
            - x86_64
            - arm64
      - axis:
          type: label-expression
          name: AVAILABLE_DIST
          values:
            - centos6
            - centos7
      - axis:
          type: dynamic
          name: DIST
          values:
            - DISTROS
      - axis:
          type: dynamic
          name: ARCH
          values:
            - ARCHS

    scm:
      - git:
          url: git@github.com:ceph/cephmetrics.git
          # Use the SSH key attached to the ceph-jenkins GitHub account.
          credentials-id: 'jenkins-build'
          skip-tag: true
          wipe-workspace: false

    triggers:
      - github

    builders:
      - shell: |
          echo "Cleaning up top-level workarea (shared among workspaces)"
          sudo rm -rf dist
          sudo rm -rf venv
          sudo rm -rf release
      # rpm build scripts
      - shell:
          !include-raw-verbatim:
            - ../../../scripts/build_utils.sh
            - ../../build/setup
            - ../../build/build_rpm

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
          - text:
              credential-id: shaman-api-key
              variable: SHAMAN_API_KEY
