- job:
    name: ceph-iscsi-config
    project-type: matrix
    defaults: global
    display-name: 'ceph-iscsi-config'
    block-downstream: false
    block-upstream: false
    concurrent: true
    parameters:
      - string:
          name: BRANCH
          description: "The git branch (or tag) to build"
          default: "main"

      - string:
          name: DISTROS
          description: "A list of distros to build for. Available options are: centos7, centos6, bionic, xenial, trusty-pbuilder, precise, wheezy, and jessie"
          default: "centos7 xenial bionic"

      - string:
          name: ARCHS
          description: "A list of architectures to build for. Available options are: x86_64"
          default: "x86_64"

      - bool:
          name: FORCE
          description: "
If this is unchecked, then nothing is built or pushed if they already exist in chacra. This is the default.

If this is checked, then the binaries will be built and pushed to chacra even if they already exist in chacra."

      - string:
          name: BUILD_VIRTUALENV
          description: "Base parent path for virtualenv locations, set to avoid issues with extremely long paths that are incompatible with tools like pip. Defaults to '/tmp/' (note the trailing slash, which is required)."
          default: "/tmp/"

    execution-strategy:
       combination-filter: DIST==AVAILABLE_DIST && ARCH==AVAILABLE_ARCH && (ARCH=="x86_64" || (ARCH == "arm64" && (DIST == "xenial" || DIST == "centos7")))
    axes:
      - axis:
          type: label-expression
          name: MACHINE_SIZE
          values:
            - small
      - axis:
          type: label-expression
          name: AVAILABLE_ARCH
          values:
            - x86_64
      - axis:
          type: label-expression
          name: AVAILABLE_DIST
          values:
            - centos7
            - xenial
            - bionic
      - axis:
          type: dynamic
          name: DIST
      - axis:
          type: dynamic
          name: DIST
          values:
            - DISTROS
      - axis:
          type: dynamic
          name: ARCH
          values:
            - ARCHS

    scm:
      - git:
          url: git@github.com:ceph/ceph-iscsi-config.git
          # Use the SSH key attached to the ceph-jenkins GitHub account.
          credentials-id: 'jenkins-build'
          branches:
            - $BRANCH
          skip-tag: true
          wipe-workspace: true

    builders:
      - shell: |
          echo "Cleaning up top-level workarea (shared among workspaces)"
          rm -rf dist
          rm -rf venv
          rm -rf release
      # debian build scripts
      - shell:
          !include-raw-verbatim:
            - ../../build/validate_deb
            - ../../../scripts/build_utils.sh
            - ../../build/setup
            - ../../build/build_deb
      # rpm build scripts
      - shell:
          !include-raw-verbatim:
            - ../../build/validate_rpm
            - ../../../scripts/build_utils.sh
            - ../../build/setup
            - ../../build/build_rpm

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
          - text:
              credential-id: chacractl-key
              variable: CHACRACTL_KEY
      - credentials-binding:
          - text:
              credential-id: shaman-api-key
              variable: SHAMAN_API_KEY
