---
- name: update apt cache
  apt:
    update_cache: yes
  become: yes

- name: install postgresql requirements
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - postgresql-common
    - postgresql-contrib
    - postgresql-server-dev-9.5
    - python-psycopg2
  tags:
    - packages

- name: ensure database service is up
  service:
    name: postgresql
    state: started
    enabled: yes
  become: yes

- name: "Build pg_hba.conf file"
  become: true
  template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/9.5/main/pg_hba.conf"

- name: make jenkins-build user
  postgresql_user:
    name: "jenkins-build"
    password: "secret"
    role_attr_flags: SUPERUSER
    login_user: postgres
  become_user: postgres
  become: yes

- service:
    name: postgresql
    state: restarted
  become: yes
