- job:
    name: ceph-website-prs
    description: This job builds PRs from github.com/ceph/ceph.io and serves them at $branch.ceph.io.
    node: www
    project-type: freestyle
    defaults: global
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    properties:
      - build-discarder:
          days-to-keep: -1
          num-to-keep: 20
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph.io

    parameters:
      - string:
          name: sha1
          description: "A pull request ID or branch, like 'origin/pr/72/head' or wip-blogpost1"

    triggers:
      - github-pull-request:
          org-list:
            - ceph
          cancel-builds-on-update: true
          trigger-phrase: 'jenkins test.*|jenkins retest.*'
          only-trigger-phrase: false
          github-hooks: true
          permit-all: false
          auto-close-on-fail: false
          status-context: "Compiling site"
          started-status: "Compiling site"
          success-status: "Site compiled successfully!"
          failure-status: "Site compilation failed"
#         This is kinda noisy if there's lots of force pushes
#         success-comment: "Site built successfully!  https://${GIT_BRANCH}.ceph.io"

    scm:
      - git:
          url: https://github.com/ceph/ceph.io
          branches:
            - origin/pr/${ghprbPullId}/merge
          refspec: +refs/pull/${ghprbPullId}/*:refs/remotes/origin/pr/${ghprbPullId}/*
          browser: auto
          skip-tag: true
          timeout: 20
          wipe-workspace: true

    builders:
      - shell:
          !include-raw:
            - ../../build/build
