---

- name: ensure ssl certs directory
  file:
    dest: /etc/ssl/certs
    state: directory
  sudo: true

- name: ensure ssl private directory
  file:
    dest: /etc/ssl/private
    state: directory
  sudo: true

- name: copy SSL cert
  copy:
    src: "{{ ssl_cert_path }}"
    dest: "/etc/ssl/certs/{{ item.fqdn }}-bundled.crt"
    mode: 0777
    force: no
  sudo: true
  notify: restart nginx
  when: nginx_hosts is defined
  with_items: nginx_hosts

- name: copy SSL key
  copy:
    src: "{{ ssl_key_path }}"
    dest: "/etc/ssl/private/{{ item.fqdn }}.key"
    force: no
  sudo: true
  notify: restart nginx
  when: nginx_hosts is defined
  with_items: nginx_hosts
