#!/bin/bash
# This script will push repository files from the signer box to the upstream repositories.
# By default it will sync all releases defined, but can optionally take one or more
# releases to sync:
#
#     sync-push hammer infernalis
#
# Since the binaries are created with a different repository layout, this
# script maps directories like "centos/6" to "rpm-$release/el6"

releases=${*:-"firefly giant hammer infernalis testing"}

ceph_sync() {
  release=$1
  deb_cmd="/opt/repos/ceph/$release/debian/jessie/* signer@download.ceph.com:/data/download.ceph.com/www/debian-$release/"
  rsync --progress --exclude '*lockfile*' -avr $deb_cmd

  for el_version in 7 8; do
    el_cmd="/opt/repos/ceph/$release/centos/$el_version/* signer@download.ceph.com:/data/download.ceph.com/www/rpm-$release/el${el_version}/"
    rsync --progress -avr $el_cmd
  done
}

for i in "${releases[@]}"
do
   ceph_sync $i
done
