#!/bin/bash

: ${2?"Usage: $0 \$project \$release \$sha1"}
  #  Script exits here if command-line parameter absent,
  #+ with following error message.
  #    usage-message.sh: 1: Usage: sync-pull $project $release $sha1

project=${1}
release=${2}
sha1=${3}

echo "sync for: $project $release"
echo "********************************************"
deb_cmd="ubuntu@chacra.ceph.com:/opt/repos/$project/$release/$sha1/debian/jessie/flavors/default/* /opt/repos/$project/$release/debian/jessie/"
echo $deb_cmd
echo "--------------------------------------------"
rsync -Lavh -e 'ssh -p 2222' --progress $deb_cmd

el7_cmd="ubuntu@chacra.ceph.com:/opt/repos/$project/$release/$sha1/centos/7/flavors/default/* /opt/repos/$project/$release/centos/7/"
echo $el7_cmd
echo "--------------------------------------------"
rsync -Lavh -e 'ssh -p 2222' --progress $el7_cmd
