#!/bin/bash -ex
# vim:ts=2 sw=2 expandtab
# This script will push repository files from the signer box to the upstream repositories.
# By default it will sync all releases defined, but can optionally take one or more
# releases to sync:
#
#     sync-push hammer infernalis
#
# Since the binaries are created with a different repository layout, this
# script maps directories like "centos/6" to "rpm-$release/el6"

# this directory is auth-protected so anxious users don't try to
# pull an in-progress release
prerelease_dir=/data/download.ceph.com/www/prerelease

releases=${*:-"quincy reef squid"}

ceph_sync() {
  release=$1
  for path in $(ls -d /opt/repos/ceph/* | grep $release | sort -V); do

    # We started using the new /opt/repos/ceph/$release-X.X.X format with Octopus.
    # Older releases have all packages in one big $release dir without a trailing "-X.X.X" so we need to adjust paths accordingly.
    if [[ "$release" =~ ^[a-n].* ]]; then
      # Nautilus and older
      newgen=false
    else
      # Octopus and newer
      newgen=true
    fi

    if $newgen; then
      version=$(echo $path | cut -d '-' -f2)
      release=$(echo $release | cut -d '-' -f1)
      ssh signer@download.ceph.com "mkdir -p ${prerelease_dir}/debian-$version"

      deb_cmd="$path/debian/jessie/* signer@download.ceph.com:${prerelease_dir}/debian-$version/"
    else
      deb_cmd="$path/debian/jessie/* signer@download.ceph.com:${prerelease_dir}/debian-$release/"
    fi
    rsync --progress --exclude '*lockfile*' -avr $deb_cmd

    for el_version in 7 8 9; do
      if $newgen; then
        ssh signer@download.ceph.com "mkdir -p ${prerelease_dir}/rpm-$version/el$el_version"

        el_cmd="$path/centos/$el_version/* signer@download.ceph.com:${prerelease_dir}/rpm-$version/el${el_version}/"
      else
        el_cmd="$path/centos/$el_version/* signer@download.ceph.com:${prerelease_dir}/rpm-$release/el${el_version}/"
      fi
      if [ -d "$path/centos/$el_version" ]; then
        rsync --progress -avr $el_cmd
      fi
    done
  done

  # Since paths are listed alphabetically/numerically in the first `for` loop, the last $version is what gets used for the new symlink below.
  if $newgen; then
    ssh signer@download.ceph.com "cd ${prerelease_dir}/; \
                                  ln -sfn debian-$version debian-$release; \
                                  ln -sfn rpm-$version rpm-$release"
  fi
}

for i in "${releases[@]}"
do
   ceph_sync $i
done

echo "Once you've tested the repos at ${prerelease_dir}, don't forget to mv them
up to the parent directory!"
