- project:
    name: ceph-container-nightly
    test:
      - all_daemons
      - collocation
      - lvm_osds
    jobs:
        - 'ceph-container-nightly-ceph_ansible-{test}'

- job-template:
    name: 'ceph-container-nightly-ceph_ansible-{test}'
    node: vagrant&&libvirt&&centos8
    concurrent: true
    defaults: global
    display-name: 'ceph-container: Nightly tests [ceph_ansible-{test}]'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-container
      - build-discarder:
          days-to-keep: -1
          num-to-keep: -1
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1

    parameters:
      - string:
          name: BRANCH
          description: "A ceph-container branch to test"
          default: main

    triggers:
      - timed: '@daily'

    scm:
      - git:
          url: https://github.com/ceph/ceph-container.git
          branches:
            - ${{BRANCH}}
          browser: auto
          timeout: 20

    builders:
      - inject:
          properties-content: |
            SCENARIO=ceph_ansible-{test}
            NIGHTLY=TRUE
      - shell:
          !include-raw-escape:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
          - username-password-separated:
              credential-id: ceph-container-quay-io
              username: REGISTRY_USERNAME
              password: REGISTRY_PASSWORD

    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                  - FAILURE
                  - ABORTED
              build-steps:
                - shell: !include-raw: ../../build/teardown
