# multiple scm requires definition of each scm with `name` so that they can be
# referenced later in `job`
# reference: http://docs.openstack.org/infra/jenkins-job-builder/scm.html
- scm:
    name: radosgw-agent
    scm:
      - git:
          url: https://github.com/ceph/radosgw-agent.git
          branches:
            - ${{sha1}}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: false
          basedir: "radosgw-agent"

- scm:
    name: ceph-build
    scm:
      - git:
          url: https://github.com/ceph/ceph-build.git
          browser-url: https://github.com/ceph/ceph-build
          timeout: 20
          skip-tag: true
          wipe-workspace: false
          basedir: "ceph-build"


- job:
    name: radosgw-agent-pull-requests
    node: trusty
    project-type: freestyle
    defaults: global
    display-name: 'radosgw-agent: Pull Requests'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - build-discarder:
          days-to-keep: 15
          num-to-keep: 30
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/radosgw-agent

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          admin-list:
            - alfredodeza
            - jdurgin
          org-list:
            - ceph
          trigger-phrase: ''
          only-trigger-phrase: false
          github-hooks: true
          permit-all: false
          auto-close-on-fail: false

    scm:
      - radosgw-agent
      - ceph-build

    builders:
      - shell:
          !include-raw-verbatim:
            - ../../../scripts/build_utils.sh
            - ../../build/build
