---

- hosts: jenkins_controller
  user: cm
  become: true
  roles:
    - ansible-jenkins
  vars:
    - nginx_processor_count: 20
    - nginx_connections: 2048
    - ansible_ssh_port: 2222
    - plugins:
      - 'ace-editor'
      - 'additional-metrics'
      - 'ant'
      - 'antisamy-markup-formatter'
      - 'apache-httpcomponents-client-4-api'
      - 'applitools-eyes'
      - 'authentication-tokens'
      - 'bouncycastle-api'
      - 'branch-api'
      - 'build-failure-analyzer'
      - 'build-history-metrics-plugin'
      - 'build-monitor-plugin'
      - 'build-user-vars-plugin'
      - 'built-on-column'
      - 'cloudbees-folder'
      - 'cobertura'
      - 'code-coverage-api'
      - 'command-launcher'
      - 'compress-artifacts'
      - 'conditional-buildstep'
      - 'configuration-as-code'
      - 'copyartifact'
      - 'credentials'
      - 'credentials-binding'
      - 'cvs'
      - 'dashboard-view'
      - 'description-setter'
      - 'display-url-api'
      - 'docker-commons'
      - 'docker-workflow'
      - 'durable-task'
      - 'dynamic-axis'
      - 'envinject'
      - 'envinject-api'
      - 'external-monitor-job'
      - 'ghprb'
      - 'git'
      - 'git-client'
      - 'github'
      - 'github-api'
      - 'github-branch-source'
      - 'github-oauth'
      - 'github-organization-folder'
      - 'git-server'
      - 'global-build-stats'
      - 'handlebars'
      - 'htmlpublisher'
      - 'icon-shim'
      - 'jackson2-api'
      - 'javadoc'
      - 'jdk-tool'
      - 'jenkins-multijob-plugin'
      - 'jquery-detached'
      - 'jsch'
      - 'junit'
      - 'ldap'
      - 'lockable-resources'
      - 'mailer'
      - 'mapdb-api'
      - 'mask-passwords'
      - 'matrix-auth'
      - 'matrix-project'
      - 'maven-plugin'
      - 'momentjs'
      - 'multiple-scms'
      - 'naginator'
      - 'nested-view'
      - 'pam-auth'
      - 'parameterized-trigger'
      - 'pipeline-build-step'
      - 'pipeline-github-lib'
      - 'pipeline-graph-analysis'
      - 'pipeline-input-step'
      - 'pipeline-milestone-step'
      - 'pipeline-model-api'
      - 'pipeline-model-declarative-agent'
      - 'pipeline-model-definition'
      - 'pipeline-model-extensions'
      - 'pipeline-rest-api'
      - 'pipeline-stage-step'
      - 'pipeline-stage-tags-metadata'
      - 'pipeline-stage-view'
      - 'plain-credentials'
      - 'postbuildscript'
      - 'preSCMbuildstep'
      - 'publish-over'
      - 'publish-over-ssh'
      - 'rebuild'
      - 'resource-disposer'
      - 'run-condition'
      - 'scm-api'
      - 'script-security'
      - 'short-workspace-path'
      - 'ssh-agent'
      - 'ssh-credentials'
      - 'ssh-slaves'
      - 'structs'
      - 'subversion'
      - 'token-macro'
      - 'translation'
      - 'trilead-api'
      - 'urltrigger'
      - 'windows-slaves'
      - 'workflow-aggregator'
      - 'workflow-api'
      - 'workflow-basic-steps'
      - 'workflow-cps'
      - 'workflow-cps-global-lib'
      - 'workflow-durable-task-step'
      - 'workflow-job'
      - 'workflow-multibranch'
      - 'workflow-scm-step'
      - 'workflow-step-api'
      - 'workflow-support'
      - 'ws-cleanup'

    - jenkins_port: 8080
    - prefix: '/build'
    - xmx: 8192
    # Email support
    #- email:
    #  smtp_host: 'mail.example.com'
    #  smtp_ssl: 'true'
    #  default_email_suffix: '@example.com'
  vars_prompt:
  - name: "okay_with_restart"
    prompt: "\nWARNING: Some tasks like updating/installing plugins will restart Jenkins.\nAre you okay with restarting the Jenkins service? (y|n)"
    default: "n"
