- job:
    name: tcmu-runner-trigger
    node: built-in
    project-type: freestyle
    defaults: global
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    properties:
      - build-discarder:
          days-to-keep: 1
          num-to-keep: 10
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/tcmu-runner
    discard-old-builds: true

    triggers:
      - github

    scm:
      - git:
          url: https://github.com/ceph/tcmu-runner.git
          branches:
            - 'origin/main*'
            - 'origin/testing*'
            - 'origin/wip*'
          skip-tag: true
          timeout: 20
          wipe-workspace: true

    builders:
      - trigger-builds:
        - project: 'tcmu-runner'
          predefined-parameters: |
            BRANCH=${{GIT_BRANCH}}
            FORCE=True
