- scm:
    name: nfs-ganesha
    scm:
      - git:
          url: https://github.com/nfs-ganesha/nfs-ganesha.git
          branches:
            - $NFS_GANESHA_BRANCH
          skip-tag: true
          wipe-workspace: true
          basedir: "nfs-ganesha"

- scm:
    name: nfs-ganesha-debian
    scm:
      - git:
          url: https://github.com/nfs-ganesha/nfs-ganesha-debian.git
          branches:
            - $NFS_GANESHA_DEBIAN_BRANCH
          skip-tag: true
          wipe-workspace: true
          basedir: "nfs-ganesha-debian"

- scm:
    name: ntirpc
    scm:
      - git:
          url: https://github.com/nfs-ganesha/ntirpc.git
          branches:
            - $NTIRPC_BRANCH
          skip-tag: true
          wipe-workspace: true
          basedir: "ntirpc"

- job:
    name: nfs-ganesha-stable
    project-type: matrix
    defaults: global
    display-name: 'nfs-ganesha-stable'
    block-downstream: false
    block-upstream: false
    properties:
      - github:
          url: https://github.com/nfs-ganesha/nfs-ganesha
    concurrent: true
    parameters:
      - string:
          name: NFS_GANESHA_BRANCH
          description: "The git branch (or tag) to build"
          default: "V2.7-stable"

      - string:
          name: NTIRPC_BRANCH
          description: "The git branch (or tag) to build"
          default: "v1.7.3"

      - string:
          name: NTIRPC_DEBIAN_BRANCH
          description: "The git branch (or tag) for debian build scripts for ntirpc"
          default: "xenial-libntirpc-1.7"

      - string:
          name: NFS_GANESHA_DEBIAN_BRANCH
          description: "The git branch (or tag) for debian build scripts for nfs-ganesha"
          default: "xenial-nfs-ganesha-download-dot-ceph-dot-com"

      - string:
          name: CEPH_SHA1
          description: "The SHA1 of the ceph branch"
          default: "3a54b2b6d167d4a2a19e003a705696d4fe619afc"

      - string:
          name: CEPH_BRANCH
          description: "The branch of Ceph to get the repo file of for libcephfs"
          default: "nautilus"

      - string:
          name: CEPH_VERSION
          description: "The version of Ceph to specify for installing ceph libraries"
          default: "14.2.0"

      - string:
          name: DISTROS
          description: "A list of distros to build for. Available options are: bionic, xenial, centos7, centos8"
          default: "centos7 centos8 xenial bionic"

      - string:
          name: ARCHS
          description: "A list of architectures to build for. Available options are: x86_64, and arm64"
          default: "x86_64"

      - bool:
          name: THROWAWAY
          description: "
Default: False. When True it will not POST binaries to chacra. Artifacts will not be around for long. Useful to test builds."
          default: false

      - bool:
          name: FORCE
          description: "
If this is unchecked, then nothing is built or pushed if they already exist in chacra. This is the default.

If this is checked, then the binaries will be built and pushed to chacra even if they already exist in chacra."
          default: true

      - string:
          name: BUILD_VIRTUALENV
          description: "Base parent path for virtualenv locations, set to avoid issues with extremely long paths that are incompatible with tools like pip. Defaults to '/tmp/' (note the trailing slash, which is required)."
          default: "/tmp/"

    execution-strategy:
       combination-filter: DIST==AVAILABLE_DIST && ARCH==AVAILABLE_ARCH && (ARCH=="x86_64" || (ARCH == "arm64" && (DIST == "xenial" || DIST == "centos7")))
    axes:
      - axis:
          type: label-expression
          name: MACHINE_SIZE
          values:
            - huge
      - axis:
          type: label-expression
          name: AVAILABLE_ARCH
          values:
            - x86_64
            - arm64
      - axis:
          type: label-expression
          name: AVAILABLE_DIST
          values:
            - centos7
            - centos8
            - xenial
            - bionic
      - axis:
          type: dynamic
          name: DIST
          values:
            - DISTROS
      - axis:
          type: dynamic
          name: ARCH
          values:
            - ARCHS
    triggers:
      - github

    scm:
      - nfs-ganesha
      - nfs-ganesha-debian
      - ntirpc

    builders:
      - shell: |
          echo "Cleaning up top-level workarea (shared among workspaces)"
          sudo rm -rf dist
          sudo rm -rf venv
          sudo rm -rf release
      # debian build scripts
      - shell:
          !include-raw-verbatim:
            - ../../build/validate_deb
            - ../../../scripts/build_utils.sh
            - ../../build/setup
            - ../../build/build_deb
      # rpm build scripts
      - shell:
          !include-raw-verbatim:
            - ../../build/validate_rpm
            - ../../../scripts/build_utils.sh
            - ../../build/setup
            - ../../build/build_rpm

    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                  - FAILURE
                  - ABORTED
              build-steps:
                - inject:
                    properties-file: ${{WORKSPACE}}/build_info
                - shell:
                    !include-raw-verbatim:
                      - ../../../scripts/build_utils.sh
                      - ../../build/failure

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
          - text:
              credential-id: chacractl-key
              variable: CHACRACTL_KEY
          - text:
              credential-id: shaman-api-key
              variable: SHAMAN_API_KEY
