#!/bin/bash

set -ex

APT_DEPS="libmysqlclient-dev libevent-dev libffi-dev libssl-dev pkg-config"
# We don't have tty-less sudo on docs.ceph.com; these deps must be installed
# manually.
#sudo apt install $APT_DEPS
