- job:
    name: teuthology-docs
    disabled: true
    node: docs
    project-type: freestyle
    defaults: global
    display-name: 'Teuthology: Docs Build'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - build-discarder:
          days-to-keep: -1
          num-to-keep: -1
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/teuthology

    triggers:
      - github

    scm:
      - git:
          url: https://github.com/ceph/teuthology.git
          branches:
            - main
          browser: auto
          timeout: 20

    builders:
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../setup/setup
            - ../../build/build
