- job:
    block-downstream: false
    block-upstream: false
    builders:
    - shell:
        !include-raw-verbatim:
          - ../../../scripts/build_utils.sh
          - ../../../scripts/setup_container_runtime.sh
          - ../../build/build
    concurrent: true
    disabled: false
    name: ceph-make-check-periodic-ppc64
    node: 'ppc64 && (installed-os-noble || centos9)'
    parameters:
    - string:
        name: PullID
        description: "The main branch ID"
        default: origin/main
    project-type: freestyle
    properties:
    - build-discarder:
        artifact-days-to-keep: -1
        artifact-num-to-keep: -1
        days-to-keep: 15
        num-to-keep: 300
    - github:
        url: https://github.com/ceph/ceph/
    quiet-period: '5'
    retry-count: '3'
    scm:
    - git:
        url: https://github.com/ceph/ceph.git
        name: origin
        branches:
          - ${{PullID}}
        refspec: +refs/heads/*:refs/remotes/origin/*
        skip-tag: true
        shallow-clone: true
        honor-refspec: true
        timeout: 20
        wipe-workspace: true
    triggers:
      - timed: '@weekly'
    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                - ABORTED
              build-steps:
                - shell:
                    !include-raw-verbatim:
                      - ../../build/kill-tests
      - xunit:
          thresholds:
            - failed:
                unstable: 0
                unstablenew: 0
                failure: 0
                failurenew: 0
          types:
            - ctest:
                pattern: "build/Testing/**/Test.xml"
                skip-if-no-test-files: true
    wrappers:
      - ansicolor
      - credentials-binding:
          - username-password-separated:
              credential-id: github-readonly-token
              username: GITHUB_USER
              password: GITHUB_PASS
          - username-password-separated:
              credential-id: dgalloway-docker-hub
              username: DOCKER_HUB_USERNAME
              password: DOCKER_HUB_PASSWORD
