---
- import_tasks: create.yml
  when: "stage == 'create'"

- import_tasks: push.yml
  when:
    - "stage == 'push'"
    - "release != 'SECURITY'"
    - tag|bool is true

# This only runs to prevent the Archive Artifacts plugin from hanging
- import_tasks: write_sha1_file.yml
  when:
    - "stage == 'push'"
    - "release == 'SECURITY'"
