---
# Note: None of this will get run when "release == 'SECURITY'"
# We want to make sure packages get pulled, signed, and pushed before publicly
# pushing the security fix. Pushing tags will be done manually by a human.

- name: clone the ceph repository
  git:
    repo: git@github.com:ceph/ceph.git
    dest: ceph
    remote: upstream
    accept_hostkey: yes
    recursive: no

# the colon appended to the v{{ version }} tag removes the previous tag
# https://git-scm.com/docs/git-push#Documentation/git-push.txt--d
- name: clear the previous remote tag
  command: git push upstream :v{{ version }}
  args:
    chdir: ceph
  ignore_errors: yes
  when: tag|bool is true

- name: add releases repo
  command: git remote add -f releases git@github.com:ceph/ceph-releases.git
  args:
    chdir: ceph
  ignore_errors: yes

- name: git fetch --all
  command: git fetch --all
  args:
    chdir: ceph

- name: "git checkout the version commit from ceph-releases"
  command: git checkout -f -B {{ branch }}-release releases/{{ branch }}-release
  args:
    chdir: ceph

- import_tasks: write_sha1_file.yml

- name: push version commit to BRANCH-release branch
  command: git push upstream {{ branch }}-release
  args:
    chdir: ceph

- name: "create pull request to merge {{ branch }}-release back into {{ branch }}"
  uri:
    url: https://api.github.com/repos/ceph/ceph/pulls
    method: POST
    status_code: 201
    headers:
      Accept: "application/vnd.github.v3+json"
      Authorization: "token {{ token }}"
    body:
      title: "v{{ version }}"
      body: "{{ pr_checklist }}"
      head: "{{ branch }}-release"
      base: "{{ branch }}"
    body_format: json
  tags: pr
  no_log: true

- name: push the newly created tag
  command: git push upstream v{{ version }}
  args:
    chdir: ceph
