---
# Note: None of this will get run when "release == 'SECURITY'"
# We want to make sure packages get pulled, signed, and pushed before publicly
# pushing the security fix. Pushing tags will be done manually by a human.

- name: Check if a pull request already exists for branch
  ansible.builtin.uri:
    url: "https://api.github.com/repos/ceph/ceph/pulls?state=open&head=ceph:{{ branch }}-release&base={{ branch }}"
    method: GET
    headers:
      Accept: "application/vnd.github.v3+json"
      Authorization: "token {{ token }}"
    return_content: true
  register: pr_check
  no_log: true   # hides token and response details safely

- name: Fail if a PR already exists
  ansible.builtin.fail:
    msg: >-
      A pull request already exists for branch '{{ branch }}-release':
      {{ pr_check.json[0].html_url }}
  when: pr_check.json | length > 0

- name: clone the ceph repository
  git:
    repo: git@github.com:ceph/ceph.git
    dest: ceph
    remote: upstream
    accept_hostkey: yes
    recursive: no

# the colon appended to the v{{ version }} tag removes the previous tag
# https://git-scm.com/docs/git-push#Documentation/git-push.txt--d
- name: clear the previous remote tag
  command: git push upstream :v{{ version }}
  args:
    chdir: ceph
  register: push_clear_remote_tag
  ignore_errors: yes
  when: tag|bool is true
  failed_when: >-
    push_clear_remote_tag is failed and
    ('remote ref does not exist' not in (push_clear_remote_tag.stderr | default('')))

- name: add releases repo
  command: git remote add -f releases git@github.com:ceph/ceph-releases.git
  args:
    chdir: ceph
  ignore_errors: yes

- name: git fetch --all
  command: git fetch --all
  args:
    chdir: ceph

- name: "git checkout the version commit from ceph-releases"
  command: git checkout -f -B {{ branch }}-release releases/{{ branch }}-release
  args:
    chdir: ceph

- import_tasks: write_sha1_file.yml

- name: push version commit to BRANCH-release branch
  command: git push upstream {{ branch }}-release
  args:
    chdir: ceph

- name: "create pull request to merge {{ branch }}-release back into {{ branch }}"
  uri:
    url: https://api.github.com/repos/ceph/ceph/pulls
    method: POST
    status_code: 201
    headers:
      Accept: "application/vnd.github.v3+json"
      Authorization: "token {{ token }}"
    body:
      title: "v{{ version }}"
      body: "{{ pr_checklist }}"
      head: "{{ branch }}-release"
      base: "{{ branch }}"
    body_format: json
  tags: pr
  no_log: true

- name: push the newly created tag
  command: git push upstream v{{ version }}
  args:
    chdir: ceph
