---
# These tasks write the version commit's sha1 to a file for
# ceph-source-dist and ceph-dev-pipeline to later consume.
#
# We write it again when running the playbook with stage=push only so
# the Archive Artifacts plugin doesn't hang indefinitely.  We don't want
# to configure the plugin to allow an empty or missing file.

- name: record commit sha1
  command: git rev-parse HEAD
  args:
    chdir: ceph
  register: commit_sha

- name: ensure ceph/dist dir exists
  file:
    path: ceph/dist
    state: directory

- name: save commit sha1 to file
  copy:
    content: "{{ commit_sha.stdout }}"
    dest: ceph/dist/sha1
