- job:
    name: ceph-ansible-docs-pull-requests
    disabled: true
    node: (small && (centos8 || trusty)) || (vagrant && libvirt && smithi)
    project-type: freestyle
    defaults: global
    display-name: 'ceph-ansible: docs pull requests'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - build-discarder:
          days-to-keep: -1
          num-to-keep: 10
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph-ansible

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          trigger-phrase: 'jenkins test docs'
          # This is set so the job can be manually triggered or by the ceph-ansible-pipeline multijob
          only-trigger-phrase: true
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "Docs"
          started-status: "checking if docs build"
          success-status: "docs built successfully "
          failure-status: "docs could not build correctly"

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible
          browser: auto
          skip-tag: true
          timeout: 20

    builders:
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/build
